CORE_INC := $(srctree)/techpack/datarmnet/core
EXTRA_CFLAGS += -I$(CORE_INC) \
    $(call cc-option,-Wno-misleading-indentation)

obj-m += rmnet_offload.o

rmnet_offload-y := rmnet_offload_state.o rmnet_offload_main.o \
		   rmnet_offload_engine.o rmnet_offload_tcp.o \
		   rmnet_offload_udp.o rmnet_offload_stats.o \
		   rmnet_offload_knob.o
