CORE_INC := $(srctree)/techpack/datarmnet/core
EXTRA_CFLAGS += -I$(CORE_INC) \
    $(call cc-option,-Wno-misleading-indentation)

obj-m += rmnet_perf_tether.o

rmnet_perf_tether-y := rmnet_perf_tether_main.o
