CORE_INC := $(srctree)/techpack/datarmnet/core
EXTRA_CFLAGS += -I$(CORE_INC) \
    $(call cc-option,-Wno-misleading-indentation)

obj-m += rmnet_shs.o

rmnet_shs-y :=  rmnet_shs_config.o \
		rmnet_shs_main.o \
		rmnet_shs_common.o \
		rmnet_shs_wq.o \
		rmnet_shs_freq.o \
		rmnet_shs_wq_mem.o \
		rmnet_shs_wq_genl.o \
		rmnet_shs_modules.o
