CORE_INC := $(srctree)/techpack/datarmnet/core
EXTRA_CFLAGS += -I$(CORE_INC) \
    $(call cc-option,-Wno-misleading-indentation)

obj-m += rmnet_aps.o

rmnet_aps-y := \
        rmnet_aps_main.o \
	rmnet_aps_genl.o
