CORE_INC := $(srctree)/techpack/datarmnet/core
EXTRA_CFLAGS += -I$(CORE_INC)

obj-m += rmnet_aps.o
ccflags-y := -I$(RMNET_CORE_INC_DIR) \
             $(call cc-option,-Wno-misleading-indentation)
rmnet_aps-y := \
        rmnet_aps_main.o \
	rmnet_aps_genl.o
