# SPDX-License-Identifier: GPL-2.0-only

DISPLAY_ROOT := $(srctree)/techpack/display

ifeq ($(CONFIG_ARCH_WAIPIO), y)
ifeq ($(CONFIG_ARCH_QTI_VM), y)
	include $(DISPLAY_ROOT)/config/gki_waipiodisptui.conf
	LINUX_INC +=	-include $(DISPLAY_ROOT)/config/gki_waipiodisptuiconf.h
else
	include $(srctree)/techpack/display/config/gki_waipiodisp.conf
	export
	LINUXINCLUDE += -include $(srctree)/techpack/display/config/gki_waipiodispconf.h
endif
endif

LINUXINCLUDE    += \
		   -I$(DISPLAY_ROOT)/include/uapi/display \
		   -I$(DISPLAY_ROOT)/include
USERINCLUDE     += -I$(DISPLAY_ROOT)/include/uapi/display

obj-$(CONFIG_DRM_MSM) += msm/
